import { Article, ArticleDetail } from "@/types/article";

export const mockArticles: Article[] = [
  {
    id: "1",
    title: "철새 이동 경로에서 포착된 희귀종 발견",
    oneLineSummary: "금강 하구에서 국내 미기록 희귀 철새가 발견됐어요.",
    cardSummary: "충남 금강 하구에서 국내 미기록 희귀 철새가 처음 포착됐다. 기후변화로 인한 이동 경로 변화가 원인으로 분석된다.",
    source: "연합뉴스",
    sourceLang: "ko",
    publishedAt: "2026-05-18T09:00:00Z",
    thumbnailUrl: "/images/bird-rare.jpg",
    category: "sky",
    subcategory: "bird",
    confidence: 0.95,
  },
  {
    id: "2",
    title: "제임스 웹 망원경, 새로운 외계행성 대기 성분 확인",
    oneLineSummary: "웹 망원경이 외계행성에서 생명 가능성 분자를 발견했어요.",
    cardSummary: "NASA 제임스 웹 망원경이 외계행성 K2-18b 대기에서 생명 관련 분자 DMS를 검출했다. 추가 관측이 필요한 상태다.",
    source: "사이언스타임즈",
    sourceLang: "ko",
    publishedAt: "2026-05-17T14:30:00Z",
    thumbnailUrl: "/images/space-webb.jpg",
    category: "sky",
    subcategory: "space",
    confidence: 0.92,
  },
  {
    id: "3",
    title: "한반도 봄철 황사, 올해 역대급 농도 기록",
    oneLineSummary: "올봄 황사 농도가 역대 최고 수준을 기록했어요.",
    cardSummary: "올해 봄 한반도 황사 농도가 역대 최고치를 경신했다. 기상청은 당분간 황사가 지속될 것으로 전망했다.",
    source: "그린포스트코리아",
    sourceLang: "ko",
    publishedAt: "2026-05-16T08:00:00Z",
    thumbnailUrl: "/images/weather-dust.jpg",
    category: "sky",
    subcategory: "weather",
    confidence: 0.97,
  },
  {
    id: "10",
    title: "수도권 초미세먼지 주의보…노약자 외출 자제 권고",
    oneLineSummary: "수도권에 초미세먼지 주의보가 발령되며 외출 자제가 권고됐어요.",
    cardSummary: "수도권 전역에 초미세먼지 주의보가 발령됐다. 환경부는 노약자와 어린이의 외출 자제를 당부했다.",
    source: "환경부",
    sourceLang: "ko",
    publishedAt: "2026-05-19T07:00:00Z",
    thumbnailUrl: "/images/sky-airpollution.jpg",
    category: "sky",
    subcategory: "air_pollution",
    confidence: 0.94,
  },
  {
    id: "4",
    title: "강원도 산불, 이틀째 확산…주민 대피령 발령",
    oneLineSummary: "강원 산불이 이틀째 번지며 주민 대피가 시작됐어요.",
    cardSummary: "강원 강릉 연곡면 산불이 이틀째 200ha를 태우며 확산 중이다. 주민 1,200명이 대피했으며 진화율은 30%에 머물고 있다.",
    source: "한겨레",
    sourceLang: "ko",
    publishedAt: "2026-05-15T11:00:00Z",
    thumbnailUrl: "/images/land-wildfire.jpg",
    category: "land",
    subcategory: "disaster",
    confidence: 0.98,
  },
  {
    id: "5",
    title: "멸종위기 수달, 한강 도심 구간서 번식 확인",
    oneLineSummary: "멸종위기 수달이 한강 도심에서 새끼를 낳았어요.",
    cardSummary: "멸종위기종 수달이 한강 도심 구간에서 번식이 확인됐다. 생태 복원 성과로 평가된다.",
    source: "연합뉴스",
    sourceLang: "ko",
    publishedAt: "2026-05-14T10:00:00Z",
    thumbnailUrl: "/images/land-otter.jpg",
    category: "land",
    subcategory: "animal",
    confidence: 0.96,
  },
  {
    id: "6",
    title: "낙동강 수계 퇴적물서 중금속 오염 심각",
    oneLineSummary: "낙동강 퇴적물에서 기준치 초과 중금속이 발견됐어요.",
    cardSummary: "낙동강 수계 퇴적물에서 기준치를 초과하는 중금속이 검출됐다. 당국이 정밀 조사에 나섰다.",
    source: "그린포스트코리아",
    sourceLang: "ko",
    publishedAt: "2026-05-13T09:30:00Z",
    thumbnailUrl: "/images/land-pollution.jpg",
    category: "land",
    subcategory: "ground_pollution",
    confidence: 0.93,
  },
  {
    id: "11",
    title: "기후변화로 한반도 매미 개체수 급증…도심 소음 피해 확산",
    oneLineSummary: "기후변화로 매미 개체수가 늘며 도심 소음 민원이 급증하고 있어요.",
    cardSummary: "기후변화 영향으로 한반도 매미 개체수가 급증하고 있다. 도심 소음 민원이 전년 대비 2배 이상 증가했다.",
    source: "한겨레",
    sourceLang: "ko",
    publishedAt: "2026-05-17T10:00:00Z",
    thumbnailUrl: "/images/land-insect.jpg",
    category: "land",
    subcategory: "insect",
    confidence: 0.88,
  },
  {
    id: "7",
    title: "남해 참돔 어획량 30% 감소…수온 상승이 원인",
    oneLineSummary: "남해 참돔이 수온 상승으로 30% 줄었어요.",
    cardSummary: "남해 참돔 어획량이 전년 대비 30% 감소했다. 수온 상승으로 인한 서식지 변화가 주요 원인이다.",
    source: "연합뉴스",
    sourceLang: "ko",
    publishedAt: "2026-05-12T13:00:00Z",
    thumbnailUrl: "/images/sea-snapper.jpg",
    category: "sea",
    subcategory: "marine_life",
    confidence: 0.91,
  },
  {
    id: "8",
    title: "동해 수심 2000m서 신종 해양 생물 발견",
    oneLineSummary: "동해 심해 2000m에서 신종 갑각류가 발견됐어요.",
    cardSummary: "동해 수심 2000m 심해에서 신종 갑각류가 발견됐다. 국내 연구팀이 학계에 공식 보고할 예정이다.",
    source: "사이언스타임즈",
    sourceLang: "ko",
    publishedAt: "2026-05-11T15:00:00Z",
    thumbnailUrl: "/images/sea-deepsea.jpg",
    category: "sea",
    subcategory: "deep_sea",
    confidence: 0.94,
  },
  {
    id: "9",
    title: "태평양 플라스틱 쓰레기 섬, 한반도 면적의 6배",
    oneLineSummary: "태평양 쓰레기 섬이 한반도의 6배 크기로 커졌어요.",
    cardSummary: "태평양 플라스틱 쓰레기 섬이 한반도 면적의 6배 규모로 확대됐다. 국제사회의 대응 촉구가 이어지고 있다.",
    source: "BBC Earth",
    sourceLang: "en",
    publishedAt: "2026-05-10T07:00:00Z",
    thumbnailUrl: "/images/sea-plastic.jpg",
    category: "sea",
    subcategory: "ocean_pollution",
    confidence: 0.89,
  },
];

export const mockArticleDetails: ArticleDetail[] = [
  {
    id: "1",
    title: "철새 이동 경로에서 포착된 희귀종 발견",
    oneLineSummary: "금강 하구에서 국내 미기록 희귀 철새가 발견됐어요.",
    cardSummary: "충남 금강 하구에서 국내 미기록 희귀 철새가 처음 포착됐다. 기후변화로 인한 이동 경로 변화가 원인으로 분석된다.",
    source: "연합뉴스",
    sourceLang: "ko",
    publishedAt: "2026-05-18T09:00:00Z",
    thumbnailUrl: "/images/bird-rare.jpg",
    category: "sky",
    subcategory: "bird",
    confidence: 0.95,
    originalUrl: "https://www.yna.co.kr/view/example-1",
    content: null,
    paragraphSummaries: [
      {
        paragraphIndex: 0,
        originalText: "금강 하구 철새 도래지에서 국내에서 한 번도 기록된 적 없는 희귀 철새가 발견돼 조류 학계의 주목을 받고 있다.",
        summary: "충남 금강 하구에서 국내 미기록 희귀 철새가 처음 포착됨.",
      },
      {
        paragraphIndex: 1,
        originalText: "발견된 새는 도요목에 속하는 종으로, 외형적 특징이 기존 국내 기록종과 다수 상이한 것으로 확인됐다.",
        summary: "도요목 계열로 추정되며 국제 전문가 검토 중임.",
      },
      {
        paragraphIndex: 2,
        originalText: "금강 하구는 매년 봄·가을 이동 철마다 수십만 마리의 철새가 거쳐 가는 동아시아 철새 이동 경로의 핵심 기착지다.",
        summary: "기후변화로 인한 이동 경로 변화가 원인으로 분석됨.",
      },
      {
        paragraphIndex: 3,
        originalText: "국립생태원 관계자는 확정적인 동정 결과가 나오기까지 수 주가 소요될 수 있다고 말했다.",
        summary: "최종 확인까지 수 주 소요 예정이며 현장 출입이 통제됨.",
      },
    ],
  },
  {
    id: "2",
    title: "제임스 웹 망원경, 새로운 외계행성 대기 성분 확인",
    oneLineSummary: "웹 망원경이 외계행성에서 생명 가능성 분자를 발견했어요.",
    cardSummary: "NASA 제임스 웹 망원경이 외계행성 K2-18b 대기에서 생명 관련 분자 DMS를 검출했다. 추가 관측이 필요한 상태다.",
    source: "사이언스타임즈",
    sourceLang: "ko",
    publishedAt: "2026-05-17T14:30:00Z",
    thumbnailUrl: "/images/space-webb.jpg",
    category: "sky",
    subcategory: "space",
    confidence: 0.92,
    originalUrl: "https://www.sciencetimes.co.kr/example-2",
    content: null,
    paragraphSummaries: [
      {
        paragraphIndex: 0,
        originalText: "제임스 웹 우주망원경이 외계행성 K2-18b의 대기에서 DMS 신호를 포착했다.",
        summary: "웹 망원경이 K2-18b 대기에서 생명 관련 분자를 검출함.",
      },
      {
        paragraphIndex: 1,
        originalText: "케임브리지대 연구팀이 NIRSpec 분광기로 대기 스펙트럼을 분석해 DMS 신호를 확인했다.",
        summary: "DMS 신호 확인됐으나 통계적 유의성 확보를 위한 추가 관측이 필요함.",
      },
      {
        paragraphIndex: 2,
        originalText: "K2-18b는 지구 질량의 8.6배인 하이션 행성으로, 이론적으로 생명체 거주 조건을 충족할 수 있다.",
        summary: "K2-18b는 이론적으로 생명체 거주 조건을 갖춘 하이션 행성임.",
      },
      {
        paragraphIndex: 3,
        originalText: "일부 천문학자들은 DMS가 비생물학적 반응으로도 생성될 수 있어 성급한 결론을 경계한다.",
        summary: "비생물학적 생성 가능성도 있어 NASA가 후속 관측을 이어갈 예정임.",
      },
    ],
  },
  {
    id: "4",
    title: "강원도 산불, 이틀째 확산…주민 대피령 발령",
    oneLineSummary: "강원 산불이 이틀째 번지며 주민 대피가 시작됐어요.",
    cardSummary: "강원 강릉 연곡면 산불이 이틀째 200ha를 태우며 확산 중이다. 주민 1,200명이 대피했으며 진화율은 30%에 머물고 있다.",
    source: "한겨레",
    sourceLang: "ko",
    publishedAt: "2026-05-15T11:00:00Z",
    thumbnailUrl: "/images/land-wildfire.jpg",
    category: "land",
    subcategory: "disaster",
    confidence: 0.98,
    originalUrl: "https://www.hani.co.kr/example-4",
    content: null,
    paragraphSummaries: [
      {
        paragraphIndex: 0,
        originalText: "강원도 강릉 연곡면 산불이 이틀째 번지며 200ha를 태우고 진화율 30%에 머물고 있다.",
        summary: "강릉 연곡면 산불이 이틀째 200ha를 태우며 진화율 30%에 머무름.",
      },
      {
        paragraphIndex: 1,
        originalText: "헬기 21대와 진화대원 800명이 투입됐으나 초속 18m의 강풍으로 진화에 어려움을 겪고 있다.",
        summary: "강풍·건조 날씨로 대규모 인력 투입에도 진화에 어려움을 겪음.",
      },
      {
        paragraphIndex: 2,
        originalText: "강릉시는 주민 1,200여 명에게 대피 명령을 내렸고, 농가·비닐하우스 등 재산 피해가 발생했다.",
        summary: "주민 1,200명 대피 및 농가·비닐하우스 수십 동 소실됨.",
      },
      {
        paragraphIndex: 3,
        originalText: "행안부가 특별교부세를 긴급 지원하고, 오후부터 바람이 약해져 진화 여건이 개선될 전망이다.",
        summary: "오후부터 바람이 약해져 진화 여건 개선이 기대됨.",
      },
    ],
  },
];
