import { Article } from "@/types/article";

export const mockArticles: Article[] = [
  {
    id: "1",
    title: "철새 이동 경로에서 포착된 희귀종 발견",
    oneLineSummary: "금강 하구에서 국내 미기록 희귀 철새가 발견됐어요.",
    source: "연합뉴스",
    sourceLang: "ko",
    publishedAt: "2026-05-18T09:00:00Z",
    thumbnailUrl: "/images/bird-rare.jpg",
    category: "sky",
    subcategory: "bird",
    confidence: 0.95,
  },
  {
    id: "2",
    title: "제임스 웹 망원경, 새로운 외계행성 대기 성분 확인",
    oneLineSummary: "웹 망원경이 외계행성에서 생명 가능성 분자를 발견했어요.",
    source: "사이언스타임즈",
    sourceLang: "ko",
    publishedAt: "2026-05-17T14:30:00Z",
    thumbnailUrl: "/images/space-webb.jpg",
    category: "sky",
    subcategory: "space",
    confidence: 0.92,
  },
  {
    id: "3",
    title: "한반도 봄철 황사, 올해 역대급 농도 기록",
    oneLineSummary: "올봄 황사 농도가 역대 최고 수준을 기록했어요.",
    source: "그린포스트코리아",
    sourceLang: "ko",
    publishedAt: "2026-05-16T08:00:00Z",
    thumbnailUrl: "/images/weather-dust.jpg",
    category: "sky",
    subcategory: "weather",
    confidence: 0.97,
  },
  {
    id: "4",
    title: "강원도 산불, 이틀째 확산…주민 대피령 발령",
    oneLineSummary: "강원 산불이 이틀째 번지며 주민 대피가 시작됐어요.",
    source: "한겨레",
    sourceLang: "ko",
    publishedAt: "2026-05-15T11:00:00Z",
    thumbnailUrl: "/images/land-wildfire.jpg",
    category: "land",
    subcategory: "disaster",
    confidence: 0.98,
  },
  {
    id: "5",
    title: "멸종위기 수달, 한강 도심 구간서 번식 확인",
    oneLineSummary: "멸종위기 수달이 한강 도심에서 새끼를 낳았어요.",
    source: "연합뉴스",
    sourceLang: "ko",
    publishedAt: "2026-05-14T10:00:00Z",
    thumbnailUrl: "/images/land-otter.jpg",
    category: "land",
    subcategory: "animal",
    confidence: 0.96,
  },
  {
    id: "6",
    title: "낙동강 수계 퇴적물서 중금속 오염 심각",
    oneLineSummary: "낙동강 퇴적물에서 기준치 초과 중금속이 발견됐어요.",
    source: "그린포스트코리아",
    sourceLang: "ko",
    publishedAt: "2026-05-13T09:30:00Z",
    thumbnailUrl: "/images/land-pollution.jpg",
    category: "land",
    subcategory: "pollution",
    confidence: 0.93,
  },
  {
    id: "7",
    title: "남해 참돔 어획량 30% 감소…수온 상승이 원인",
    oneLineSummary: "남해 참돔이 수온 상승으로 30% 줄었어요.",
    source: "연합뉴스",
    sourceLang: "ko",
    publishedAt: "2026-05-12T13:00:00Z",
    thumbnailUrl: "/images/sea-snapper.jpg",
    category: "sea",
    subcategory: "marine_life",
    confidence: 0.91,
  },
  {
    id: "8",
    title: "동해 수심 2000m서 신종 해양 생물 발견",
    oneLineSummary: "동해 심해 2000m에서 신종 갑각류가 발견됐어요.",
    source: "사이언스타임즈",
    sourceLang: "ko",
    publishedAt: "2026-05-11T15:00:00Z",
    thumbnailUrl: "/images/sea-deepsea.jpg",
    category: "sea",
    subcategory: "deep_sea",
    confidence: 0.94,
  },
  {
    id: "9",
    title: "태평양 플라스틱 쓰레기 섬, 한반도 면적의 6배",
    oneLineSummary: "태평양 쓰레기 섬이 한반도의 6배 크기로 커졌어요.",
    source: "BBC Earth",
    sourceLang: "en",
    publishedAt: "2026-05-10T07:00:00Z",
    thumbnailUrl: "/images/sea-plastic.jpg",
    category: "sea",
    subcategory: "ocean_pollution",
    confidence: 0.89,
  },
];
